<h1 style="text-align: center;">NumPy</h1>

Using NumPy, a developer can perform the following operations :−

- Mathematical and logical operations on arrays.

- Fourier transforms and routines for shape manipulation.

- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

<h2>ndarray Object</h2>
<p>The most important object defined in NumPy is an N-dimensional array type called ndarray.<br>
Take a look at the following examples to understand better.</p>

Example 1

In [128]:
import numpy as np
a = np.array([1,2,3])
print (a)

[1 2 3]


Example 2

In [129]:
# more than one dimensions 
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


Example 3

In [130]:
# minimum dimensions
import numpy as np
a = np.array([1,2,3,4,5],ndmin = 2)
print(a)

[[1 2 3 4 5]]


Example 4

In [131]:
# dtype parameter
import numpy as np
a = np.array([1,2,4], dtype= complex)
print(a)

[1.+0.j 2.+0.j 4.+0.j]


The ndarray object consists of contiguous one-dimensional segment of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order (C style) or a column-major order (FORTRAN or MatLab style).

<h2>Data Types</h2>

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects :

- Type of data (integer, float or Python object)

- Size of data

- Byte order (little-endian or big-endian)

- In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.

- If data type is a subarray, its shape and data type

A dtype object is constructed using the following syntax :
```
numpy.dtype(object, align, copy)
```

The parameters are −

- Object − To be converted to data type object

- Align − If true, adds padding to the field to make it similar to C-struct

- Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object

Example 1

In [132]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int64) 
print(dt)

int64


Example 2

In [133]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print(dt) 

int32


Example 3

In [134]:
# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
print(dt)

>i4


The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

Example 4

In [135]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

[('age', 'i1')]


Example 5

In [136]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10),(20),(30)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


Example 6

In [137]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8),('roll',np.int8)]) 
a = np.array([(10,2),(20,4),(30,1)], dtype = dt) 
print(a['age'],a['roll'])

[10 20 30] [2 4 1]


<h2>Shape of Array</h2>

You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes.

Example 1

In [167]:
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


<h3>2 Dimension Array</h3>

In [3]:
### 2 dimension array
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

(2, 3)


<h3>3 Dimension Array</h3>

Higher dimension can be constructed as follow:

In [2]:
### 3 dimension array
import numpy as np
d = np.array([[[1, 2,3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])
print(d)
print("\n",d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 (2, 2, 3)


<h2>numpy.ones()</h2>

```
numpy.ones(shape, dtype=float, order='C')
```

Here,

**Shape**: is the shape of the array

**Dtype**: is the datatype. It is optional. The default value is float64

**Order**: Default is C which is an essential row style.

Example 1

In [9]:
# Creating array with iniital value as 1.
import numpy as np
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


Same as once() you can create a array with all initial value as 0.

In [20]:
import numpy as np
z = np.zeros((2,2))
print(z)

[[0. 0.]
 [0. 0.]]


Example 2

In [23]:
# numpy zero with datatype
import numpy as np
np.zeros((2,2), dtype=np.int16)


array([[0, 0],
       [0, 0]], dtype=int16)

<h2>numpy.reshape()</h2>

In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. The syntax is
```
numpy.reshape(a, newShape, order='C')
```
Here,

**a**: Array that you want to reshape

**newShape**: The new desires shape

**Order**: Default is C which is an essential row style.

Example 1

In [35]:
# reshaping numpy array
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print("Before :\n",e,"\n")
print("After :\n",e.reshape(3,2))

Before :
 [[1 2 3]
 [4 5 6]] 

After :
 [[1 2]
 [3 4]
 [5 6]]


<h2>Flatten Data</h2>

When you deal with some neural network like convnet, you need to flatten the array. You can use flatten(). The syntax is

```
numpy.flatten(order='C')
```
Here,<br>
**Order**: Default is C which is an essential row style.

In [40]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print("Before :\n",e,"\n")
print("After :\n",e.flatten(order='f')) #flatten by column

Before :
 [[1 2 3]
 [4 5 6]] 

After :
 [1 4 2 5 3 6]


<h2>numpy.hstack()</h2>

**What is hstack?**<br>
With hstack you can appened data horizontally. This is a very convinient function in Numpy.<br>Lets study it with an example:

In [52]:
## Horitzontal Stack
import numpy as np
f = np.array([[1,2,3],[0,11,12]])
g = np.array([[4,5,6],[7,8,9]])
print(f,"\n",g)
print('Horizontal Append:', np.hstack((f, g)))

[[ 1  2  3]
 [ 0 11 12]] 
 [[4 5 6]
 [7 8 9]]
Horizontal Append: [[ 1  2  3  4  5  6]
 [ 0 11 12  7  8  9]]


**What is vstack?**<br>
With vstack you can appened data vertically.<br>Lets study it with an example:

In [54]:
## Vertical Stack
import numpy as np
f = np.array([[1,2,3],[0,11,12]])
g = np.array([[4,5,6],[7,8,9]])
print(f,"\n",g)
print('Horizontal Append:', np.vstack((f, g)))

[[ 1  2  3]
 [ 0 11 12]] 
 [[4 5 6]
 [7 8 9]]
Horizontal Append: [[ 1  2  3]
 [ 0 11 12]
 [ 4  5  6]
 [ 7  8  9]]


<h2>Generate Random Numbers</h2>

To generate random numbers for Gaussian distribution use<br>

```
numpy.random.normal(loc, scale, size)
```
Here<br>

**Loc**: the mean. The center of distribution<br>
**scale**: standard deviation<br>
**Size**: number of returns<br>

Example 1

In [57]:
## Generate random nmber from normal distribution
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.47972221 5.40159898 4.82862315 5.44689414 5.52136841 5.16430457
 5.1985366  4.18697146 5.50225797 4.72428279]


<h2>numpy.asarray()</h2>

The asarray()function is used when you want to convert an input to an array. The input could be a lists, tuple, ndarray, etc.

Syntax:
```
numpy.asarray(data, dtype=None, order=None)[source]
```
Here,

**data**: Data that you want to convert to an array

**dtype**: This is an optional argument. If not specified, the data type is inferred from the input data

**Order**: Default is C which is an essential row style. Other option is F (Fortan-style)

Example 1

In [60]:
import numpy as np
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [61]:
np.array(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Matrix is immutable. You can use asarray if you want to add modification in the original array. Let's see if any change occurs when you want to change the value of the third rows with the value 2

In [62]:
np.asarray(A)[2]=2 # np.asarray(A) converts the matrix into array
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


<h2>numpy.arrange()</h2>


**Whay is Arrange?**<br>
Sometimes, you want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function

Syntax:
```
numpy.arange(start, stop,step) 
```
Here,<br>
**Start**: Start of interval<br>
**Stop**: End of interval<br>
**Step**: Spacing between values. Default step is 1<br>

In [65]:
import numpy as np
print(np.arange(1, 14, 4))

[ 1  5  9 13]


<h2>numpy.linspace()</h2>

Linspace gives evenly spaced samples.<br>

Syntax:<br>
```
numpy.linspace(start, stop, num, endpoint)
```
Here,<br>

**Start**: Starting value of the sequence<br>
**Stop**: End value of the sequence<br>
**Num**: Number of samples to generate. Default is 50<br>
**Endpoint**: If True (default), stop is the last value. If False, stop value is not included.<br>

Example 1

In [68]:
import numpy as np
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
# If you do not want to include the last digit in the interval, you can set endpoint to false
import numpy as np
np.linspace(1.0, 5.0, num=10, endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

<h2>LogSpace</h2>

LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.<br>
Syntax:<br>
```
numpy.logspace(start, stop, num, endpoint)
```

Example 1

In [73]:
import numpy as np
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

<h2>Indexing and slicing</h2>

Slicing data is trivial with numpy. We will slice the matrice "e". Note that, in Python, you need to use the brackets to return the rows or columns

Example 1

In [75]:
## Slice
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


Remember with numpy the first array/column starts at 0.

In [77]:
## First column
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In Python, like many other languages,

- The values before the comma stand for the rows
- The value on the rights stands for the columns.
- If you want to select a column, you need to add : before the column index.
- : means you want all the rows from the selected column.

In [78]:
print('Second column:', e[:,1])

Second column: [2 5]


In [81]:
print(e[1, :2])

[4 5]


<h2>NumPy Statistical Functions</h2>

Numpy is equipped with the robust statistical function as listed below

| Function | Numpy |
|----------|-------|
| Min | np.min() |
| Max | np.max() |
| Mean | np.mean() |
| Median | np.median() |
| Standard deviation | np.std() |

Example 1 Statiscal Function

In [83]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.186971460266426
5.5213684119134365
5.145456028643356
5.300067791325129
0.4167086787551181


<h2>numpy.dot()</h2>

Numpy is powerful library for matrices computation. For instance, you can compute the dot product with np.dot

Syntax

numpy.dot(x, y, out=None)
Here,

**x,y**: Input arrays. x and y both should be 1-D or 2-D for the function to work

**out**: This is the output argument.For 1-D array scalar is returned. Other wise ndarray

Example 1

In [85]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

<h2>np.matmul()</h2>

The Numpu matmul() function is used to return the matrix product of 2 arrays. Here is how it works

1) 2-D arrays, it returns normal product

2) Dimensions > 2, the product is treated as a stack of matrix

3) 1-D array is first promoted to a matrix, and then the product is calculated

Syntax:
```
numpy.matmul(x, y, out=None)
```
Here,<br>

**x,y**: Input arrays. scalars not allowed

**out**: This is optional parameter. Usually output is stored in ndarray

Example 1

In [87]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
re = np.matmul(h, i)
print(re)

[[19 22]
 [43 50]]


<h2>Determinant</h2>

if you need to compute the determinant, you can use np.linalg.det(). Note that numpy takes care of the dimension.

In [88]:
## Determinant 2*2 matrix
### 5*8-7*6
np.linalg.det(i)

-2.000000000000005