<h1 style="text-align: center;">NumPy</h1>

Using NumPy, a developer can perform the following operations :−

- Mathematical and logical operations on arrays.

- Fourier transforms and routines for shape manipulation.

- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

<h2>ndarray Object</h2>
<p>The most important object defined in NumPy is an N-dimensional array type called ndarray.<br>
Take a look at the following examples to understand better.</p>

Example 1

In [128]:
import numpy as np
a = np.array([1,2,3])
print (a)

[1 2 3]


Example 2

In [129]:
# more than one dimensions 
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


Example 3

In [130]:
# minimum dimensions
import numpy as np
a = np.array([1,2,3,4,5],ndmin = 2)
print(a)

[[1 2 3 4 5]]


Example 4

In [131]:
# dtype parameter
import numpy as np
a = np.array([1,2,4], dtype= complex)
print(a)

[1.+0.j 2.+0.j 4.+0.j]


The ndarray object consists of contiguous one-dimensional segment of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order (C style) or a column-major order (FORTRAN or MatLab style).

<h2>Data Types</h2>

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects :

- Type of data (integer, float or Python object)

- Size of data

- Byte order (little-endian or big-endian)

- In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.

- If data type is a subarray, its shape and data type

A dtype object is constructed using the following syntax :
```
numpy.dtype(object, align, copy)
```

The parameters are −

- Object − To be converted to data type object

- Align − If true, adds padding to the field to make it similar to C-struct

- Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object

Example 1

In [132]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int64) 
print(dt)

int64


Example 2

In [133]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print(dt) 

int32


Example 3

In [134]:
# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
print(dt)

>i4


The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

Example 4

In [135]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

[('age', 'i1')]


Example 5

In [136]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10),(20),(30)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


Example 6

In [137]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8),('roll',np.int8)]) 
a = np.array([(10,2),(20,4),(30,1)], dtype = dt) 
print(a['age'],a['roll'])

[10 20 30] [2 4 1]


<h2>Shape of Array</h2>

You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes.

Example 1

In [167]:
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


<h3>2 Dimension Array</h3>

In [173]:
### 2 dimension array
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

(2, 3)


<h3>3 Dimension Array</h3>

In [ ]:
Higher dimension can be constructed as follow:

In [174]:
### 3 dimension array
d = np.array([[[1, 2,3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
